### ISSUE TITLE
Update to latest fathom js

### ISSUE THREAD

**Issue by mirshko** [unstacked/fathom-client#2]
Seems they updated their tracking code? 

```html
<!-- Fathom - beautiful, simple website analytics -->
<script src="https://cdn.usefathom.com/3.js" site="MY SITE ID"></script>
<!-- / Fathom -->
```

**Comment by derrickreimer** [comment]
Thanks for the heads up. I'm in touch with Jack from Fathom about this. It sounds like they are making some more updates shortly to the script, so we'll standby for the moment. This library is still working in it's current state.

**Comment by mirshko** [comment]
word! glad to hear! thanks for the notice

**Comment by bobheadxi** [comment]
https://github.com/unstacked/fathom-client/pull/3 makes the switch to the new client, and looks like @derrickreimer is making some additional changes - looking forward to seeing a new release!
