### ISSUE TITLE
nextjs + custom domain throws an error

### ISSUE THREAD

**Issue by 2075** [unstacked/fathom-client#4]
Hi there

When using fathom-client inside a nextjs app with a custom url, i receive console errors and somehow we get redirected it seems with another 302:

```
		if (process.env.NODE_ENV === 'production') {
			Fathom.load('//subdomain.domain.tld')
			Fathom.setSiteId('12345678')
			Fathom.trackPageview()
		}
```

```
10:39:40.807 The script from “https://app.usefathom.com/login” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
10:39:40.816 SyntaxError: expected expression, got '<'
```

**Comment by derrickreimer** [comment]
Hi there, I'm not entirely sure why the redirect is happening. At the moment we are just using the URL as the `src` on the script tag: https://github.com/unstacked/fathom-client/blob/master/src/index.ts#L31

Fathom did update the structure of the their script though, which I intend to update here shortly.

**Comment by 2075** [comment]
Hey Derrick! Yes, I thought so, too, and wrote a support request to Fathom, will keep u posted.

**Comment by 2075** [comment]
seems like the issue was the transition from deferred to async loading, used a local copy for now.
