### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by bobheadxi** [unstacked/fathom-client#5]
@derrickreimer any word on when you might tag + publish a new release for this package? :) mostly interested in #3 and the changes you've made since

**Comment by derrickreimer** [comment]
I'll get one out this week!

**Comment by bobheadxi** [comment]
Thanks! Looks like custom domains only work with the new script, so this would be very helpful to have 🎉

**Comment by derrickreimer** [comment]
Version 3.0 release!
